# AI/ML Lab

## Assignment 5

## 2019BTECS00058 Devang K

## Batch: T7

### Design and Implementation of Decision Tree Algorithm for classification problem.

We shall implement Decision Tree Classifier using the Scikit for the dataset of Tripadvisor reviews over 10 categories. We shall train the model by providing data of 7 categories and predicting the final 3. The accuracy shall then be obtained.

In [12]:
import graphviz
import csv
from sklearn import tree
import numpy
from sklearn import preprocessing
from sklearn.metrics import mean_squared_error

lab_enc = preprocessing.LabelEncoder()

We import the dataset

In [2]:
listOfData = []
with open('tripadvisor_review.csv', newline='') as csvfile:
    spamreader = csv.reader(csvfile, delimiter=',', quotechar='|')
    for row in spamreader:
        newRow = []
        for r in row:
            try:
                newRow.append(float(r))
            except:
                newRow.append(r)
        listOfData.append(newRow[1:])
    listOfData = listOfData[1:]

We shall have 900 of the rows for training and 10 for predictions and calculating the run-off.

In [3]:
X = []
Y = []
for i in range(900):
    X.append(numpy.array(([i]+listOfData[i])[:7]))
    Y.append(numpy.array(([i]+listOfData[i])[7:]))
X = numpy.array(X)
Y = numpy.array(Y)

In [4]:
predictX = []
predictY = []
for i in range(901, 911):
    predictX.append(numpy.array(([i]+listOfData[i])[:7]))
    predictY.append(numpy.array(([i]+listOfData[i])[7:]))
predictX = numpy.array(predictX)
predictY = numpy.array(predictY)

We now train the models:

In [7]:
clf = tree.DecisionTreeRegressor()
clf = clf.fit(X, Y)

Let's check the predictions.

In [10]:
predictedResult = clf.predict(predictX)
print(predictedResult)

[[3.19 2.79 1.79 2.82]
 [3.18 2.77 1.98 2.62]
 [3.18 2.74 0.96 2.46]
 [3.18 2.82 1.47 3.06]
 [3.18 2.78 1.38 3.02]
 [3.18 2.74 1.54 2.56]
 [3.2  2.95 1.25 2.32]
 [3.18 3.22 1.47 2.82]
 [3.18 2.82 1.47 3.06]
 [3.18 3.29 2.18 2.9 ]]


Let's calculate the error from the true and the predicted result.

In [18]:
print("Error is:", mean_squared_error(predictY, predictedResult, squared=False))

Error is: 0.2074355807309574


Thus, we implemented the Decision Tree Classification for predicting the results with high accuracy. We made use of the Tripadvisor reviews dataset and made use of sci-kit learn library.